lvl4projct/basic_app/urls.py
from django.urls import path
from basic_app import views

#Template tagging
app_name = 'app'

urlpatterns = [
    path('relative/',views.relative, name= 'relative'),
    path('other/',views.other , name= 'other'),
]

lvl4projct/lvl4projct/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name= 'index'),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls'))
]

lvl4projct/basic_app/models.py
from django.db import models

# Create your models here.

lvl4projct/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request, 'basic_app/index.html',context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

lvl4projct/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index'%}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'app:other'%}">other</a></li>
        </ul>

      </div>

    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>
  </body>
</html>

lvl4projct/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h1>this is index.html page showing!</h1>
    <h1>{{text|cut:'world'}}</h1>
    <h1>{{number|add:'99'}}</h1>
        {% endblock %}

lvl4projct/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>welcome to other</h1>
    <h2>This is an example of inheritence</h2>
    {% endblock %}

lvl4projct/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to relative url template</h1>

    <a href="{% url 'app:other' %}">the other page</a>
    <a href="{% url 'admin:index'%}">link to admin</a>
  </body>
</html>